version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: blog-training-db
    volumes:
      - db-data:/var/lib/postgresql/blog_training_db_development/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  minio:
    image: quay.io/minio/minio:latest
    container_name: example-minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_SITE_REGION: ap-northeast-1
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
